### ISSUE TITLE
xorg-x11-utils

### ISSUE THREAD

**Issue by citizenserious** [pzim-devdata/volumouse#5]
There is no more package by the name xorg-x11-utils.
Could not find a similar.

```
$ sudo dnf install xorg-x11-utils

No match for argument: xorg-x11-utils
Error: Unable to find a match: xorg-x11-utils
```

**Comment by pzim-devdata** [comment]
hello,

I don't have Fedora, so I can't really help you.

You can try the Snap version : https://snapcraft.io/install/x11-utils-snap/fedora

You can also install python3-xlib  : `pip install python3-xlib` or `python3 -m pip install python3-xlib`

**Comment by citizenserious** [comment]
Thanks for the fast reply and giving us volumouse (:

It was just `sudo dnf install python3-xlib` & `sudo dnf install python3` 
It works, just had to select the top right edge.

I just can't get it to work on my second monitors left edge, had me confused, probably a resolution problem.

`xrandr | grep '*' | awk '{print $1}'`

gives me out:
2400x1350
1920x1080

Tried every possible resolution which could make sense. I have a notebook screen (settings show: 1920x1080) and a monitor to its left (settings show: 1920x1080). When setting volumouse to 1920x1080 I can use the right top and left top corner of the notebook screen but not of the Monitor (makes sense). When set to default, or 3840x2160 or 4320x2430 just the right top corner works. I can't figure out why, but it is certainly not a package problem :D

**Comment by pzim-devdata** [comment]
Did you try (2400+1920) = 4320x1080 ?

**Comment by citizenserious** [comment]
Yes, tried that too. 
The odd thing is the sometimes it works and sometimes it don't. Without changing any settings.
The service does start correctly via autostart. So the service is definitely running, a restart of it won't help either.
This is so random that I just can't figure out what is going on here. 
But when it works (just in the top right and top left corner of the right screen of two, but anyway) I love it.
