### ISSUE TITLE
xlib installation

### ISSUE THREAD

**Issue by Jammmmm** [pzim-devdata/volumouse#6]
First, thanks so much for volumouse! I'm a long time user of the Windows version so your version is *very* much appreciated :)

I noticed the requirements line has been removed in README.md, but under Linux Mint, I had to install xlib manually. Thankfully you had mentioned this in a previous issue.

Have you considered adding this information into the "Install dependancies" section so other users can benefit?
"pip install python3-xlib" or "python3 -m pip install python3-xlib" or "apt install python3-xlib" (I had to use this one under Linux Mint).

**Comment by pzim-devdata** [comment]
Hello,

Thank you. I was also using Volumouse on Windows, that why I made this for Linux ;-)

Normally if you install x11-utils : `apt-get install x11-utils`, python3-xlib should be installed.

I will restore the requirements line.

Thanks

**Comment by Jammmmm** [comment]
I have x11-utils installed, but I didn't have python3-xlib installed. No idea why, but no big deal.

Thanks again for this great program/script! :)

**Comment by pzim-devdata** [comment]
Did you tried the version V1.0 of volumouse : https://github.com/pzim-devdata/volumouse/files/15465154/volumouse.py.zip

Could you tell me what you think about it ?

Thanks !

**Comment by Jammmmm** [comment]
I've just given it a try and it works fine, except for the following:

```
Do you want to create an autostart entry for volumouse ? (Y/n)
(Volumouse will automatically start when the computer start)
If not, volumouse autostart entry will be removed ...

n


No autostart entry will be add for volumouse !

If an autostart entry was previously created, it will be deleted ...
rm: cannot remove '/home/user/.config/autostart/volumouse.desktop': No such file or directory
```

I selected the option to not create the autostart entry since I like to start software myself, but it still tried to remove the .desktop file.

I don't think it should be trying to remove the .desktop file because I may have put one in there manually.

**Comment by pzim-devdata** [comment]
Ok thank you. 

I will remember this issue when I will upload Volumouse V1. 

I will close the issue, but if you have any suggestion do not hesitate to reopen it.

Thanks !
